from pymilvus import connections, Collection

# ================= 配置 =================
HOST = "127.0.0.1"
PORT = "19531"

# 两个表的名称
COL_BUGGY = "fuzz_stable_v3"          # Fuzzer 留下的“案发现场”
COL_CLEAN = "repro_exact_simulation"  # 刚才脚本新建的“干净表”

# 目标 ID 和 查询条件
TARGET_ID = 3588
FIELD = "c4"
# c4 <= 7.315...
EXPR = "id == 3588 and c4 <= 7.3154750146117635" 

# 颜色代码
RED = "\033[91m"
GREEN = "\033[92m"
CYAN = "\033[96m"
BOLD = "\033[1m"
RESET = "\033[0m"

def check_collection(col_name):
    print(f"   Connecting to '{col_name}'...")
    try:
        col = Collection(col_name)
        col.load()
        
        # 1. 验身：确认数据是一样的
        res_data = col.query(f"id == {TARGET_ID}", output_fields=[FIELD])
        if not res_data:
            return None, "ID Not Found"
        val = res_data[0][FIELD]
        
        # 2. 验毒：执行 Bug 查询
        res_bug = col.query(EXPR, output_fields=[FIELD])
        count = len(res_bug)
        
        return val, count
    except Exception as e:
        return None, str(e)

def main():
    print("\n" + "=" * 70)
    print(f"{BOLD}⚔️  MILVUS A/B TEST: OLD vs NEW COLLECTION{RESET}")
    print("=" * 70)
    print("Hypothesis: The bug depends on the collection's internal state (segments/compaction),\nnot just the data itself.")
    
    print(f"\n🔌 Connecting to {HOST}:{PORT}...")
    connections.connect("default", host=HOST, port=PORT)

    # -------------------------------------------------
    # 测试 Table A (Buggy)
    # -------------------------------------------------
    print(f"\n{BOLD}👉 Table A: '{COL_BUGGY}' (Generated by Fuzzer){RESET}")
    val_a, count_a = check_collection(COL_BUGGY)
    
    status_a = ""
    if count_a == 1:
        status_a = f"{RED}BUG FOUND (Returned 1 row){RESET}"
    else:
        status_a = f"{GREEN}Clean (Returned 0 rows){RESET}"

    print(f"   - Data Value (c4): {val_a}")
    print(f"   - Query Result:    {status_a}")

    # -------------------------------------------------
    # 测试 Table B (Clean)
    # -------------------------------------------------
    print(f"\n{BOLD}👉 Table B: '{COL_CLEAN}' (Reloaded from JSON){RESET}")
    val_b, count_b = check_collection(COL_CLEAN)
    
    status_b = ""
    if count_b == 1:
        status_b = f"{RED}BUG FOUND (Returned 1 row){RESET}"
    else:
        status_b = f"{GREEN}Clean (Returned 0 rows){RESET}"

    print(f"   - Data Value (c4): {val_b}")
    print(f"   - Query Result:    {status_b}")

    # -------------------------------------------------
    # 最终对比
    # -------------------------------------------------
    print("\n" + "=" * 70)
    print(f"{BOLD}📊 FINAL COMPARISON REPORT{RESET}")
    print("=" * 70)
    
    print(f"{'Metric':<20} | {'Table A (Old)':<25} | {'Table B (New)':<25}")
    print("-" * 75)
    
    # 对比数据值
    match_data = "✅ MATCH" if val_a == val_b else "❌ DIFF"
    val_str_a = str(val_a) if val_a is not None else "None"
    val_str_b = str(val_b) if val_b is not None else "None"
    print(f"{'Data (c4)':<20} | {val_str_a:<25} | {val_str_b:<25} ({match_data})")
    
    # 对比查询结果
    print(f"{'Query Result':<20} | {str(count_a):<25} | {str(count_b):<25}")
    
    print("-" * 75)
    
    if val_a == val_b and count_a != count_b:
        print(f"\n{RED}{BOLD}🚨 CONCLUSION: INCONSISTENCY DETECTED!{RESET}")
        print("Both tables contain the EXACT same data (c4=None).")
        print("However, Milvus executes the query differently depending on the collection.")
        print("This proves the bug lies in the INTERNAL STATE (Segments/Index) of Table A.")
    else:
        print("\nTest Inconclusive.")

if __name__ == "__main__":
    main()