import random
import numpy as np
import math
from milvus_fuzz_oracle import DataManager, COLLECTION_NAME
from pymilvus import connections, Collection

# ================= 配置 =================
SEED = 999
HOST = "127.0.0.1"
PORT = "19531"
# 随机抽查的 ID 列表，务必包含出问题的 3588
CHECK_IDS = [0, 100, 3588, 4999, random.randint(1, 4998)]

def is_equal(val_local, val_remote):
    """
    智能比较函数
    1. 处理 None
    2. 处理 浮点数精度误差
    3. 处理 普通值
    """
    # 1. 都是 None
    if val_local is None and val_remote is None:
        return True, "Both None"
    
    # 2. 一个 None 一个不是
    if val_local is None or val_remote is None:
        return False, f"Mismatch (Local: {val_local}, Remote: {val_remote})"
    
    # 3. 浮点数比较 (允许 1e-6 的微小误差)
    if isinstance(val_local, (float, np.floating)) or isinstance(val_remote, float):
        try:
            # 注意：Milvus 可能会有 float32/float64 的精度转换
            diff = abs(float(val_local) - float(val_remote))
            if diff < 1e-5:
                return True, f"Match (Diff: {diff:.2e})"
            else:
                return False, f"Float Mismatch (Local: {val_local}, Remote: {val_remote})"
        except:
            pass

    # 4. 普通比较
    if val_local == val_remote:
        return True, "Match"
    else:
        return False, f"Mismatch (Local: {val_local}, Remote: {val_remote})"

def run_verification():
    print("=" * 60)
    print(f"🧬 Data Consistency Verification (Seed: {SEED})")
    print("=" * 60)

    # 1. 生成本地基准数据 (Ground Truth)
    print("1️⃣  Regenerating Local Data (Seed 999)...")
    random.seed(SEED); np.random.seed(SEED)
    dm = DataManager()
    dm.generate_schema()
    dm.generate_data()
    df = dm.df
    print("    -> Done.")

    # 2. 连接 Milvus
    print("2️⃣  Fetching Remote Data from Milvus...")
    connections.connect("default", host=HOST, port=PORT)
    col = Collection(COLLECTION_NAME)
    col.load()

    # 3. 逐行比对
    all_passed = True
    
    # 我们对比前 10 个标量字段，足以证明随机序列的一致性
    fields_to_check = [f"c{i}" for i in range(10)] 

    for target_id in CHECK_IDS:
        print(f"\n🔍 Verifying ID: {target_id}")
        
        # 获取本地行
        local_row = df[df["id"] == target_id].iloc[0]
        
        # 获取远程行
        res = col.query(f"id == {target_id}", output_fields=fields_to_check)
        if not res:
            print(f"❌ Critical Error: ID {target_id} not found in Milvus!")
            all_passed = False
            continue
        remote_row = res[0]

        # 逐字段比对
        row_passed = True
        for field in fields_to_check:
            v_local = local_row[field]
            v_remote = remote_row[field]
            
            # Pandas 的 NaN 需要转为 None 才能和 Milvus 的 None 对比
            if isinstance(v_local, float) and np.isnan(v_local):
                v_local = None
            
            ok, msg = is_equal(v_local, v_remote)
            
            status_icon = "✅" if ok else "❌"
            if not ok:
                row_passed = False
                all_passed = False
                print(f"   - Field {field}: {status_icon} {msg}")
            else:
                # 只打印几个关键的，避免刷屏，或者打印出有值的
                if field in ['c0', 'c4', 'c9']: 
                    print(f"   - Field {field}: {status_icon} Local={v_local} | Remote={v_remote}")

        if row_passed:
            print(f"   🎉 ID {target_id} is CONSISTENT.")
        else:
            print(f"   ⚠️ ID {target_id} has inconsistencies!")

    print("\n" + "=" * 60)
    if all_passed:
        print("🏆 FINAL RESULT: PERFECT MATCH")
        print("Proof: The data in Milvus was indeed generated by Seed 999.")
        print("The NULL value in ID 3588 is not a coincidence, it is mathematically guaranteed.")
    else:
        print("💥 FINAL RESULT: DATA MISMATCH FOUND")

if __name__ == "__main__":
    run_verification()